/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Login;

import Business.Business;
import Business.PersonDirectory;
import Business.UserAccDirectory;
import Business.UserClass;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohan
 */
public class ManagePersonDirectJPanel extends javax.swing.JPanel {
   private JPanel userProcessContainer;
    private UserAccDirectory userAccDirect;
    private PersonDirectory personDirect;
    private UserClass uc;
    private Business b;
    /**
     * Creates new form ManagePersonDirectJPanel
     */


   public ManagePersonDirectJPanel(JPanel upc, Business b) {
        initComponents();
       this.userProcessContainer = upc;
       this.userAccDirect = userAccDirect;
       this.personDirect = personDirect;
       this.b = b;
       populateTable();
               addComponentListener(new ComponentAdapter()
                {
                    @Override
                    public void componentShown(ComponentEvent evt){
                    populateTable();
                }
                });
    }

       public void populateTable(){
       int rowCount = HrjTable.getRowCount();
        DefaultTableModel dm = (DefaultTableModel)HrjTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            dm.removeRow(i);
        }
        //DefaultTableModel dm = (DefaultTableModel)adminjTable.getModel();
        dm.setRowCount(0);
        for (UserClass uc : b.getUserAccDirect().getUserAccDirect())
        {
            Object data[] = new Object[5];
            data[0] = uc.getPerson().getFirstName();
            data[1] = uc.getPerson().getLasttName();
            data[2] = uc.getUserName();
            data[3] = uc.getPassword();
            data[4] = uc.getUserAccType();
            dm.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HrjTable = new javax.swing.JTable();
        addpersonjButton = new javax.swing.JButton();
        updatepersonjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        HrjTable.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        HrjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Username", "Password", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HrjTable);
        if (HrjTable.getColumnModel().getColumnCount() > 0) {
            HrjTable.getColumnModel().getColumn(0).setResizable(false);
            HrjTable.getColumnModel().getColumn(1).setResizable(false);
            HrjTable.getColumnModel().getColumn(2).setResizable(false);
            HrjTable.getColumnModel().getColumn(3).setResizable(false);
            HrjTable.getColumnModel().getColumn(4).setResizable(false);
        }

        addpersonjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addpersonjButton.setText("Add Person Roles >>");
        addpersonjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpersonjButtonActionPerformed(evt);
            }
        });

        updatepersonjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        updatepersonjButton.setText("Update Person Roles >>");
        updatepersonjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepersonjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Available Person Accounts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatepersonjButton)
                            .addComponent(addpersonjButton))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(addpersonjButton)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatepersonjButton)
                    .addComponent(jButton3))
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addpersonjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpersonjButtonActionPerformed
        // TODO add your handling code here:
        RegisterCustJPanel awajp = new RegisterCustJPanel(userProcessContainer, b);
        userProcessContainer.add("RegisterCustJPanel",awajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addpersonjButtonActionPerformed

    private void updatepersonjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepersonjButtonActionPerformed
        // TODO add your handling code here:
        UpdateCustJPanel awajp = new UpdateCustJPanel(userProcessContainer, b);
        userProcessContainer.add("UpdateCustJPanel",awajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updatepersonjButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HrjTable;
    private javax.swing.JButton addpersonjButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updatepersonjButton;
    // End of variables declaration//GEN-END:variables
}
