/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Login;

import Business.*;
import Business.UserAccDirectory;
import java.awt.CardLayout;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohan
 */
public class ManageUserAccJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccDirectory userAccDirect;
    private PersonDirectory personDirect;
    private UserClass userclass;
    private Business b;

    /**
     * Creates new form ManageUserAccJPanel
     */


   public ManageUserAccJPanel(JPanel upc, Business b, UserAccDirectory userAccDirect) {
                initComponents();
        this.userProcessContainer = upc;
        this.userAccDirect = userAccDirect;
        this.personDirect = personDirect;
        this.b = b;
        populateTable();
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent evt) {
                populateTable();
            }
        });
    }

    public void populateTable() {
        int rowCount = adminjTable.getRowCount();
        DefaultTableModel dm = (DefaultTableModel) adminjTable.getModel();
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        //DefaultTableModel dm = (DefaultTableModel)adminjTable.getModel();
        dm.setRowCount(0);
        for (UserClass uc : b.getUserAccDirect().getUserAccDirect()) {
            Object data[] = new Object[5];
            data[0] = uc.getPerson().getFirstName();
            data[1] = uc.getPerson().getLasttName();
            data[2] = uc.getUserName();
            data[3] = uc.getPassword();
            data[4] = uc.getUserAccType();
            dm.addRow(data);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminjTable = new javax.swing.JTable();
        adduseraccjButton = new javax.swing.JButton();
        updateuseraccjButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Available User Accounts");

        adminjTable.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        adminjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "User Name", "Password", "Role/Designation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(adminjTable);
        if (adminjTable.getColumnModel().getColumnCount() > 0) {
            adminjTable.getColumnModel().getColumn(0).setResizable(false);
            adminjTable.getColumnModel().getColumn(1).setResizable(false);
            adminjTable.getColumnModel().getColumn(2).setResizable(false);
            adminjTable.getColumnModel().getColumn(3).setResizable(false);
            adminjTable.getColumnModel().getColumn(4).setResizable(false);
        }

        adduseraccjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        adduseraccjButton.setText("Add User Roles >>");
        adduseraccjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduseraccjButtonActionPerformed(evt);
            }
        });

        updateuseraccjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        updateuseraccjButton.setText("Update User Roles >>");
        updateuseraccjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateuseraccjButtonActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 630, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adduseraccjButton)
                                    .addComponent(updateuseraccjButton))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(adduseraccjButton)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateuseraccjButton)
                    .addComponent(jButton3))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adduseraccjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduseraccjButtonActionPerformed
        // TODO add your handling code here:
        CreateJPanel awajp = new CreateJPanel(userProcessContainer, b);
        userProcessContainer.add("CreateJPanel", awajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_adduseraccjButtonActionPerformed

    private void updateuseraccjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateuseraccjButtonActionPerformed
        // TODO add your handling code here:
        UpdateJPanel awajp = new UpdateJPanel(userProcessContainer, b);
        userProcessContainer.add("UpdateJPanel", awajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updateuseraccjButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adduseraccjButton;
    private javax.swing.JTable adminjTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateuseraccjButton;
    // End of variables declaration//GEN-END:variables
}
