/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Login;

import Business.Business;
import Business.Person;
import Business.UserAccDirectory;
import Business.UserClass;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Rohan
 */
public class manageJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccDirectory userAccDirect;
    private UserClass uc;
    private Business b;
    /**
     * Creates new form AdminJPanel
     */



   public manageJPanel(JPanel upc, UserClass uc, Business b) {
       initComponents();
       this.userProcessContainer = upc;
       this.userAccDirect = userAccDirect;
       this.uc = uc;
       this.b = b;

        fnamejTextField.setText(uc.getPerson().getFirstName());
        LnamejTextField.setText(uc.getPerson().getLasttName());
        unamejTextField.setText(uc.getUserName());
        managerolejTextField.setText(uc.getUserAccType());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        unamejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fnamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LnamejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        managerolejTextField = new javax.swing.JTextField();
        manageUserAccountjButton = new javax.swing.JButton();

        jButton2.setText("Manage Person Directory >>");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("You logged in as:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("UserName:");

        unamejTextField.setEditable(false);
        unamejTextField.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("First Name:");

        fnamejTextField.setEditable(false);
        fnamejTextField.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        fnamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamejTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Last Name:");

        LnamejTextField.setEditable(false);
        LnamejTextField.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LnamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnamejTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("User Role:");

        managerolejTextField.setEditable(false);
        managerolejTextField.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        manageUserAccountjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        manageUserAccountjButton.setText("Manage User Accounts >>");
        manageUserAccountjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(managerolejTextField)
                            .addComponent(unamejTextField))))
                .addContainerGap(551, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageUserAccountjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(managerolejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119)
                .addComponent(manageUserAccountjButton)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LnamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnamejTextFieldActionPerformed

    private void fnamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamejTextFieldActionPerformed

    private void manageUserAccountjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountjButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccJPanel awajp = new ManageUserAccJPanel(userProcessContainer, b, userAccDirect);
        userProcessContainer.add("ManageUserAccJPanel",awajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageUserAccountjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LnamejTextField;
    private javax.swing.JTextField fnamejTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton manageUserAccountjButton;
    private javax.swing.JTextField managerolejTextField;
    private javax.swing.JTextField unamejTextField;
    // End of variables declaration//GEN-END:variables
}
