/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Login;

import Business.Business;
import Business.Person;
import Business.UserAccDirectory;
import Business.UserClass;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Rohan
 */
public class UpdateJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccDirectory userAccDirect;
    private Business b;

    /**
     * Creates new form UpdateJPanel
     */

    public UpdateJPanel(JPanel upc, Business b) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccDirect = userAccDirect;
        this.b = b;
        for (UserClass uc : b.getUserAccDirect().getUserAccDirect()) {
            updateChoosejComboBox.addItem(uc);
        }
        unamejTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        unamejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        updatejButton = new javax.swing.JButton();
        savejButton = new javax.swing.JButton();
        clearjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        updateadminjPasswordField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        updateChoosejComboBox = new javax.swing.JComboBox<>();
        updateRolejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        activejRadioButton = new javax.swing.JRadioButton();
        disabledjRadioButton = new javax.swing.JRadioButton();

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Define Role:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("UserName:");

        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        savejButton.setText("Save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        clearjButton.setText("Clear");
        clearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Update");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Choose Person:");

        updateChoosejComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Account Status:");

        buttonGroup1.add(activejRadioButton);
        activejRadioButton.setText("Active");
        activejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activejRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(disabledjRadioButton);
        disabledjRadioButton.setText("Disabled");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(408, 408, 408))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(savejButton)
                        .addGap(122, 122, 122)
                        .addComponent(updatejButton)
                        .addGap(147, 147, 147)
                        .addComponent(clearjButton)
                        .addGap(145, 145, 145))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(updateChoosejComboBox, 0, 253, Short.MAX_VALUE)
                        .addComponent(unamejTextField)
                        .addComponent(updateadminjPasswordField)
                        .addComponent(updateRolejTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(activejRadioButton)
                        .addGap(31, 31, 31)
                        .addComponent(disabledjRadioButton)))
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(updateChoosejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(unamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(updateadminjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(updateRolejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(activejRadioButton)
                    .addComponent(disabledjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatejButton)
                    .addComponent(savejButton)
                    .addComponent(clearjButton)
                    .addComponent(jButton1))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageUserAccJPanel panel = (ManageUserAccJPanel) component;
        panel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void activejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activejRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activejRadioButtonActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
        String hashedPassword = UserClass.generateHash(updateadminjPasswordField.getText());
        try {
            UserClass uc = (UserClass) updateChoosejComboBox.getSelectedItem();
            //Person p = b.getPersonDirect().searchPerson(name);
            //UserClass uc = b.getUserAccDirect().addUserClass();
            uc.setPassword(hashedPassword);
            uc.setUserAccType(updateRolejTextField.getText());
            if (buttonGroup1.isSelected(activejRadioButton.getModel())) {
                uc.setFlag(true);
            } else {
                uc.setFlag(false);
            }
            savejButton.setEnabled(false);
            updatejButton.setEnabled(true);
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, "Account updated successfully");
        } catch (Exception e) {
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, "Invalid Entry.Please enter correct values", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_savejButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        // TODO add your handling code here:
        unamejTextField.setEnabled(true);
        updateadminjPasswordField.setEnabled(true);
        updateRolejTextField.setEnabled(true);
        updatejButton.setEnabled(false);


    }//GEN-LAST:event_updatejButtonActionPerformed

    private void comboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxItemStateChanged
        // TODO add your handling code here:
        int state = evt.getStateChange();
        if(state == ItemEvent.SELECTED){
            UserClass uc = (UserClass) updateChoosejComboBox.getSelectedItem();
            unamejTextField.setText(uc.getUserName());
            updateadminjPasswordField.setText(uc.getPassword());
            updateRolejTextField.setText(uc.getUserAccType());
        }
    }//GEN-LAST:event_comboboxItemStateChanged

    private void clearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearjButtonActionPerformed
        // TODO add your handling code here:
        unamejTextField.setText("");
        updateadminjPasswordField.setText("");
        updateRolejTextField.setText("");
    }//GEN-LAST:event_clearjButtonActionPerformed
    private void populate() {
        unamejTextField.setEnabled(false);
        updateadminjPasswordField.setEnabled(false);
        updateRolejTextField.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activejRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearjButton;
    private javax.swing.JRadioButton disabledjRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton savejButton;
    private javax.swing.JTextField unamejTextField;
    private javax.swing.JComboBox<UserClass> updateChoosejComboBox;
    private javax.swing.JTextField updateRolejTextField;
    private javax.swing.JPasswordField updateadminjPasswordField;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
