/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Login;

import Business.Business;
import Business.Person;
import Business.UserAccDirectory;
import Business.UserClass;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Rohan
 */
public class UpdateCustJPanel extends javax.swing.JPanel {
   private JPanel userProcessContainer;
    private UserAccDirectory userAccDirect;
    private Business b;
    /**
     * Creates new form UpdateCustJPanel
     */


   public UpdateCustJPanel(JPanel upc, Business b) {
        initComponents();
                this.userProcessContainer = upc;
       this.userAccDirect = userAccDirect;
       this.b = b;
        for (UserClass uc : b.getUserAccDirect().getUserAccDirect()) {
            updateChoosejComboBox.addItem(uc);
        }
        unamejTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        unamejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        updatecustjPasswordField = new javax.swing.JPasswordField();
        updatejButton = new javax.swing.JButton();
        savejButton = new javax.swing.JButton();
        clearjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        updateChoosejComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        updateRolejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        activejRadioButton = new javax.swing.JRadioButton();
        disabledjRadioButton = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Update");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("UserName:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Password:");

        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        savejButton.setText("Save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        clearjButton.setText("Clear");
        clearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearjButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Choose Person:");

        updateChoosejComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statechanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Define Role:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Account Status:");

        buttonGroup2.add(activejRadioButton);
        activejRadioButton.setText("Active");
        activejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activejRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(disabledjRadioButton);
        disabledjRadioButton.setText("Disabled");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(savejButton)
                .addGap(132, 132, 132)
                .addComponent(updatejButton)
                .addGap(139, 139, 139)
                .addComponent(clearjButton)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(updateChoosejComboBox, 0, 251, Short.MAX_VALUE)
                        .addComponent(unamejTextField)
                        .addComponent(updatecustjPasswordField)
                        .addComponent(updateRolejTextField)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(activejRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(disabledjRadioButton))))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(updateChoosejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(unamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(updatecustjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateRolejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(activejRadioButton)
                    .addComponent(disabledjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatejButton)
                    .addComponent(savejButton)
                    .addComponent(clearjButton)
                    .addComponent(jButton1))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageUserAccJPanel panel = (ManageUserAccJPanel) component;
        panel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
          String hashedPassword = UserClass.generateHash(updatecustjPasswordField.getText());
        try {
            UserClass uc = (UserClass) updateChoosejComboBox.getSelectedItem();
            //Person p = b.getPersonDirect().searchPerson(name);
            //UserClass uc = b.getUserAccDirect().addUserClass();
            uc.setPassword(hashedPassword);
            uc.setUserAccType(updateRolejTextField.getText());
            if (buttonGroup2.isSelected(activejRadioButton.getModel())) {
                uc.setFlag(true);
            } else {
                uc.setFlag(false);
            }
            savejButton.setEnabled(false);
            updatejButton.setEnabled(true);
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, "Account updated successfully");
        } catch (Exception e) {
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, "Invalid Entry.Please enter correct values", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_savejButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        // TODO add your handling code here:
         unamejTextField.setEnabled(true);
        updatecustjPasswordField.setEnabled(true);
        updateRolejTextField.setEnabled(true);
        updatejButton.setEnabled(false);
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void statechanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_statechanged
        // TODO add your handling code here:
        int state = evt.getStateChange();
        if(state == ItemEvent.SELECTED){
            UserClass uc = (UserClass) updateChoosejComboBox.getSelectedItem();
            unamejTextField.setText(uc.getUserName());
            updatecustjPasswordField.setText(uc.getPassword());
            updateRolejTextField.setText(uc.getUserAccType());
        }
    }//GEN-LAST:event_statechanged

    private void clearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearjButtonActionPerformed
        // TODO add your handling code here:
        unamejTextField.setText("");
        updatecustjPasswordField.setText("");
        updateRolejTextField.setText("");
    }//GEN-LAST:event_clearjButtonActionPerformed

    private void activejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activejRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activejRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activejRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clearjButton;
    private javax.swing.JRadioButton disabledjRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton savejButton;
    private javax.swing.JTextField unamejTextField;
    private javax.swing.JComboBox<UserClass> updateChoosejComboBox;
    private javax.swing.JTextField updateRolejTextField;
    private javax.swing.JPasswordField updatecustjPasswordField;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
