/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rohan
 */
public class ManageAccountJPanel extends javax.swing.JPanel {

    private JPanel UserProcessContainer;
    private AccountDirectory accountDirectory;
    /**
     * Creates new form ManageAccountJPanel
     */
     ManageAccountJPanel(JPanel UserProcessContainer, AccountDirectory accountDirectory) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.accountDirectory = accountDirectory;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createButtonjButton = new javax.swing.JButton();
        ManageAccountjButton = new javax.swing.JButton();

        createButtonjButton.setText("Create Account");
        createButtonjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonjButtonActionPerformed(evt);
            }
        });

        ManageAccountjButton.setText("Manage Account");
        ManageAccountjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccountjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageAccountjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(createButtonjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(868, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createButtonjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(ManageAccountjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonjButtonActionPerformed
        // TODO add your handling code here:
       createAccountJPanel createJPanel = new createAccountJPanel(UserProcessContainer,accountDirectory);
       UserProcessContainer.add("createAccountJPanel", createJPanel);
       CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
       layout.next(UserProcessContainer);
       
    }//GEN-LAST:event_createButtonjButtonActionPerformed

    private void ManageAccountjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccountjButtonActionPerformed
        // TODO add your handling code here:
       ManageJPanel manageJPanel = new ManageJPanel(UserProcessContainer,accountDirectory);
       UserProcessContainer.add("ManageJPanel", manageJPanel);
       CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
       layout.next(UserProcessContainer);
        
    }//GEN-LAST:event_ManageAccountjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageAccountjButton;
    private javax.swing.JButton createButtonjButton;
    // End of variables declaration//GEN-END:variables
}
