/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustInterface;
import CustDetails.*;
import java.awt.Image;
import java.io.File;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javafx.scene.control.SplitPane;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rohan
 */
public class CreateCust extends javax.swing.JPanel {

    /**
     * Creates new form CreateCust
     */
    private Customer customer;
    //private String filename;
    public CreateCust(Customer customer) {
        initComponents();
        this.customer=customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        natinternationalgrp = new javax.swing.ButtonGroup();
        activeinactivegrp = new javax.swing.ButtonGroup();
        debtcreditgrp = new javax.swing.ButtonGroup();
        checkingsavinggrp = new javax.swing.ButtonGroup();
        Heading = new javax.swing.JLabel();
        personalDetails = new javax.swing.JLabel();
        Fname1 = new javax.swing.JLabel();
        fnameTxtfield = new javax.swing.JTextField();
        Fname2 = new javax.swing.JLabel();
        lnameTxtField = new javax.swing.JTextField();
        Fname3 = new javax.swing.JLabel();
        dobTxtField = new javax.swing.JTextField();
        Fname = new javax.swing.JLabel();
        ssnTxtField = new javax.swing.JTextField();
        Addresslabel = new javax.swing.JLabel();
        addLine1 = new javax.swing.JLabel();
        addLine1Txtfield = new javax.swing.JTextField();
        addLine2 = new javax.swing.JLabel();
        add2TxtField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTxtfield = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        countryTxtfield = new javax.swing.JTextField();
        ziplabel = new javax.swing.JLabel();
        ZipcodeTxtField = new javax.swing.JTextField();
        Licenselabel1 = new javax.swing.JLabel();
        licenseTypeLabel1 = new javax.swing.JLabel();
        LicenseIssueDateLabel1 = new javax.swing.JLabel();
        LicenseExpDateLabel1 = new javax.swing.JLabel();
        lscissueDateTxtfield = new javax.swing.JTextField();
        ExpDateTxtfield = new javax.swing.JTextField();
        LicenenumTxtfield = new javax.swing.JTextField();
        LicensenumLabel1 = new javax.swing.JLabel();
        LicenseStateIssuedLabel1 = new javax.swing.JLabel();
        StateLicenseIssuedTxtfield = new javax.swing.JTextField();
        creditCardLabel1 = new javax.swing.JLabel();
        BankNameLabel = new javax.swing.JLabel();
        issueDateTxtfield1 = new javax.swing.JTextField();
        BkissuedateLabel = new javax.swing.JLabel();
        bnkissueDateTxtfield = new javax.swing.JTextField();
        BankNameLabel2 = new javax.swing.JLabel();
        bnkexpDateTxtfield = new javax.swing.JTextField();
        BankNameLabel3 = new javax.swing.JLabel();
        BnkcadnumTxtfield = new javax.swing.JTextField();
        BankNameLabel4 = new javax.swing.JLabel();
        NameoncardTxtfield = new javax.swing.JTextField();
        AccLabel = new javax.swing.JLabel();
        AcctypeLAbel = new javax.swing.JLabel();
        checkingAccRadioButton = new javax.swing.JRadioButton();
        SavingaccRadioButton = new javax.swing.JRadioButton();
        FABankNameLabel = new javax.swing.JLabel();
        FAbnknameTxtfield = new javax.swing.JTextField();
        FABankAddLabel = new javax.swing.JLabel();
        FABnkAddTxtfield = new javax.swing.JTextField();
        FAbnkstatusLabel = new javax.swing.JLabel();
        ActiveRadioButton = new javax.swing.JRadioButton();
        inactiveRadioButton = new javax.swing.JRadioButton();
        createbutton = new javax.swing.JButton();
        NationalRadioButton2 = new javax.swing.JRadioButton();
        IntlRadioButton3 = new javax.swing.JRadioButton();
        clearbutton = new javax.swing.JButton();
        debtRadioButton = new javax.swing.JRadioButton();
        creditRadioButton = new javax.swing.JRadioButton();
        BalanceStatus = new javax.swing.JLabel();
        LicenseTypeTxtfield = new javax.swing.JTextField();
        AcctypeTextField = new javax.swing.JTextField();
        AccStatusTxtField = new javax.swing.JTextField();
        BalanceStatusTxtfield = new javax.swing.JTextField();
        AttachjButton = new javax.swing.JButton();
        imagejTextField = new javax.swing.JTextField();
        imagejLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBorder(new javax.swing.border.MatteBorder(null));

        Heading.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Heading.setText("      Enter Customer Details");

        personalDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        personalDetails.setText("Personal Details");

        Fname1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Fname1.setText("First Name:");

        Fname2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Fname2.setText("Last Name:");

        Fname3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Fname3.setText("Date Of Birth:");

        Fname.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Fname.setText("Social Security Number:");

        ssnTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnTxtFieldActionPerformed(evt);
            }
        });

        Addresslabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Addresslabel.setText("Address");

        addLine1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        addLine1.setText("Address Line 1:");

        addLine2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        addLine2.setText("Address Line 2:");

        cityLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cityLabel.setText("City:");

        countryLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        countryLabel.setText("Country:");

        ziplabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ziplabel.setText("Zipcode:");

        Licenselabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Licenselabel1.setText("License Data");

        licenseTypeLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        licenseTypeLabel1.setText("License Type:");

        LicenseIssueDateLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LicenseIssueDateLabel1.setText("Issue Date:");

        LicenseExpDateLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LicenseExpDateLabel1.setText("Expiry Date:");

        lscissueDateTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lscissueDateTxtfieldActionPerformed(evt);
            }
        });

        ExpDateTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpDateTxtfieldActionPerformed(evt);
            }
        });

        LicensenumLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LicensenumLabel1.setText("License No.:");

        LicenseStateIssuedLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LicenseStateIssuedLabel1.setText("State License Issued:");

        creditCardLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        creditCardLabel1.setText("Credit Card Details");

        BankNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BankNameLabel.setText("Bank Name:");

        issueDateTxtfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueDateTxtfield1ActionPerformed(evt);
            }
        });

        BkissuedateLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BkissuedateLabel.setText("Issue Date:");

        bnkissueDateTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnkissueDateTxtfieldActionPerformed(evt);
            }
        });

        BankNameLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BankNameLabel2.setText("Expiry Date:");

        bnkexpDateTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnkexpDateTxtfieldActionPerformed(evt);
            }
        });

        BankNameLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BankNameLabel3.setText("Card No.:");

        BnkcadnumTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnkcadnumTxtfieldActionPerformed(evt);
            }
        });

        BankNameLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BankNameLabel4.setText("Name on the card:");

        NameoncardTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameoncardTxtfieldActionPerformed(evt);
            }
        });

        AccLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AccLabel.setText("Financial Account Details");

        AcctypeLAbel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        AcctypeLAbel.setText("Account Type:");

        checkingsavinggrp.add(checkingAccRadioButton);
        checkingAccRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        checkingAccRadioButton.setText("Checking Account");
        checkingAccRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingAccRadioButtonActionPerformed(evt);
            }
        });

        checkingsavinggrp.add(SavingaccRadioButton);
        SavingaccRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        SavingaccRadioButton.setText("Saving Account");
        SavingaccRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingaccRadioButtonActionPerformed(evt);
            }
        });

        FABankNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FABankNameLabel.setText("Bank Name:");

        FAbnknameTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAbnknameTxtfieldActionPerformed(evt);
            }
        });

        FABankAddLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FABankAddLabel.setText("Bank Address:");

        FABnkAddTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FABnkAddTxtfieldActionPerformed(evt);
            }
        });

        FAbnkstatusLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FAbnkstatusLabel.setText("Status:");

        activeinactivegrp.add(ActiveRadioButton);
        ActiveRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ActiveRadioButton.setText("Active");
        ActiveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActiveRadioButtonActionPerformed(evt);
            }
        });

        activeinactivegrp.add(inactiveRadioButton);
        inactiveRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        inactiveRadioButton.setText("Inactive");
        inactiveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inactiveRadioButtonActionPerformed(evt);
            }
        });

        createbutton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        createbutton.setText("Submit");
        createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbuttonActionPerformed(evt);
            }
        });

        natinternationalgrp.add(NationalRadioButton2);
        NationalRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        NationalRadioButton2.setText("National");
        NationalRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalRadioButton2ActionPerformed(evt);
            }
        });

        natinternationalgrp.add(IntlRadioButton3);
        IntlRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        IntlRadioButton3.setText("International");
        IntlRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntlRadioButton3ActionPerformed(evt);
            }
        });

        clearbutton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        debtcreditgrp.add(debtRadioButton);
        debtRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        debtRadioButton.setText("Debt");
        debtRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debtRadioButtonActionPerformed(evt);
            }
        });

        debtcreditgrp.add(creditRadioButton);
        creditRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        creditRadioButton.setText("Credit");
        creditRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditRadioButtonActionPerformed(evt);
            }
        });

        BalanceStatus.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BalanceStatus.setText("Balance Status");

        AcctypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcctypeTextFieldActionPerformed(evt);
            }
        });

        AttachjButton.setText("Attach");
        AttachjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachjButtonActionPerformed(evt);
            }
        });

        imagejLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        imagejLabel.setText("                 Affix Image Here");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("*");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("*");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("The fields marked * are mandatory. The form will not go to the next steps if the fields are left empty.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BankNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LicenseStateIssuedLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LicensenumLabel1)
                            .addComponent(LicenseExpDateLabel1)
                            .addComponent(creditCardLabel1)
                            .addComponent(AccLabel)
                            .addComponent(FABankNameLabel)
                            .addComponent(ziplabel)
                            .addComponent(LicenseIssueDateLabel1)
                            .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BkissuedateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BankNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BankNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AcctypeLAbel)
                                .addGap(287, 287, 287)
                                .addComponent(SavingaccRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(AcctypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Heading))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Fname3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(dobTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(Fname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Fname2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGap(79, 79, 79)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(fnameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ssnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 66, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imagejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(906, 906, 906))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personalDetails)
                            .addComponent(Licenselabel1)
                            .addComponent(licenseTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(addLine2)
                                            .addComponent(addLine1))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addLine1Txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(add2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cityTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ZipcodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(NationalRadioButton2)
                                                .addGap(27, 27, 27)
                                                .addComponent(IntlRadioButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LicenseTypeTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(countryTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(159, 159, 159)
                                                .addComponent(imagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(AttachjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(countryLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(BalanceStatusTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(FAbnkstatusLabel)
                                            .addGap(366, 366, 366)
                                            .addComponent(AccStatusTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(StateLicenseIssuedTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(BankNameLabel4)
                                                        .addGap(36, 36, 36)
                                                        .addComponent(NameoncardTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(FABankAddLabel)
                                                            .addComponent(BalanceStatus))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(FABnkAddTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(ActiveRadioButton)
                                                                    .addComponent(debtRadioButton))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(creditRadioButton)
                                                                    .addComponent(inactiveRadioButton))))))
                                                .addComponent(LicenenumTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ExpDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lscissueDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(issueDateTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bnkissueDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bnkexpDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BnkcadnumTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(checkingAccRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(FAbnknameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel4))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(365, 365, 365)
                                    .addComponent(createbutton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clearbutton))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(personalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Heading)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fnameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fname2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fname3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fname)
                            .addComponent(ssnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(Addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLine1Txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(imagejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttachjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ziplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZipcodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Licenselabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NationalRadioButton2)
                    .addComponent(IntlRadioButton3)
                    .addComponent(LicenseTypeTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseIssueDateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lscissueDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExpDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LicenseExpDateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LicenenumTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(LicensenumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseStateIssuedLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StateLicenseIssuedTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(creditCardLabel1)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankNameLabel)
                    .addComponent(issueDateTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BkissuedateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnkissueDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankNameLabel2)
                    .addComponent(bnkexpDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BnkcadnumTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameoncardTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(AccLabel)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkingAccRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AcctypeLAbel)
                        .addComponent(AcctypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SavingaccRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FABankNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FAbnknameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FABnkAddTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FABankAddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FAbnkstatusLabel)
                    .addComponent(ActiveRadioButton)
                    .addComponent(inactiveRadioButton)
                    .addComponent(AccStatusTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalanceStatus)
                    .addComponent(debtRadioButton)
                    .addComponent(creditRadioButton)
                    .addComponent(BalanceStatusTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createbutton)
                    .addComponent(clearbutton))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ssnTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnTxtFieldActionPerformed

    private void lscissueDateTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lscissueDateTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lscissueDateTxtfieldActionPerformed

    private void ExpDateTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpDateTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpDateTxtfieldActionPerformed

    private void issueDateTxtfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueDateTxtfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueDateTxtfield1ActionPerformed

    private void bnkissueDateTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnkissueDateTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnkissueDateTxtfieldActionPerformed

    private void bnkexpDateTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnkexpDateTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnkexpDateTxtfieldActionPerformed

    private void BnkcadnumTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnkcadnumTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BnkcadnumTxtfieldActionPerformed

    private void NameoncardTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameoncardTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameoncardTxtfieldActionPerformed

    private void checkingAccRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingAccRadioButtonActionPerformed
        // TO display the selected account type in the radio button
        
        AcctypeTextField.setText(checkingAccRadioButton.getText());
        
    }//GEN-LAST:event_checkingAccRadioButtonActionPerformed

    private void SavingaccRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingaccRadioButtonActionPerformed
        // TODO add your handling code here:
        
        AcctypeTextField.setText(SavingaccRadioButton.getText());
    }//GEN-LAST:event_SavingaccRadioButtonActionPerformed

    private void FAbnknameTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAbnknameTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FAbnknameTxtfieldActionPerformed

    private void FABnkAddTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FABnkAddTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FABnkAddTxtfieldActionPerformed

    private void createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbuttonActionPerformed
        // TO CREATE A NEW ENTRY FOR CUSTOMER
        
        customer.setFirstname(fnameTxtfield.getText());
        customer.setLastname(lnameTxtField.getText());
        customer.setDob(dobTxtField.getText());
        //Date CustomerDob=customer.getDob();
        //SimpleDateFormat dob = new SimpleDateFormat("mm-dd-yy"); 
       //Date birthday = customer.parseDate(dobTxtField.getText());
        //dobTxtField.setText(sf.format(CustomerDob));
        //Customer setDob = customer.setDob(birthday);
        //Customer setDob = customer.setDob(birthDay);
        //DateFormat df = DateFormat.getDateInstance();
        // df = ((DateFormat) customer.setDob(dobTxtField.getText()));
        
        
        
        int ss = Integer.parseInt(ssnTxtField.getText());
        customer.setSsn(ss);
        //customer.setSsn(ssnTxtField.getText());
        
        Address add = new Address();
        add.setAddline1(addLine1Txtfield.getText());
        add.setAddline2(add2TxtField.getText());
        add.setCity(cityTxtfield.getText());
        add.setCountry(countryTxtfield.getText());
        
        Integer d = Integer.parseInt(ZipcodeTxtField.getText());
        add.setZipcode(d);      
        //add.setZipcode(ZipcodeTxtField.getText());
        customer.setAdd(add);
        
        //licenseDetails.setLicenseType(licen)
        LicenseDetails ld=new LicenseDetails();
        ld.setLicenseType(LicenseTypeTxtfield.getText());
        
        //SimpleDateFormat lsf = new SimpleDateFormat("mm-dd-yy"); 
        //Date lscissue = Date.parseDate(lscissueDateTxtfield.getText());
        //ld.setIssueDate(lscissue);
        
        ld.setIssueDate(lscissueDateTxtfield.getText());
        ld.setExpDate(ExpDateTxtfield.getText());
        
        int lsc = Integer.parseInt(LicenenumTxtfield.getText());
        ld.setLicenseNum(lsc);
        //ld.setLicenseNum(LicenenumTxtfield.getText());
        
        ld.setStatelicenseIssued(StateLicenseIssuedTxtfield.getText());
        customer.setLicenseDetails(ld);
        
        CreditCardInfo cd = new CreditCardInfo();
        cd.setBnkName(issueDateTxtfield1.getText());
        
        int crd = Integer.parseInt(BnkcadnumTxtfield.getText());
        cd.setCardNum(crd);  
        //cd.setCardNum(BnkcadnumTxtfield.getText());
        cd.setExpDate(bnkexpDateTxtfield.getText());
        cd.setIssueDate(bnkissueDateTxtfield.getText());
        cd.setNameOnCard(NameoncardTxtfield.getText());
        customer.setCreditCard(cd);
        
        FinancialAccountInfo fa = new FinancialAccountInfo();
        fa.setAccType(AcctypeTextField.getText());
        fa.setBnkName(FAbnknameTxtfield.getText());
        fa.setBnkAdd(FABnkAddTxtfield.getText());
        fa.setStatus(AccStatusTxtField.getText());
        fa.setBalanceStatus(BalanceStatusTxtfield.getText());
        customer.setFinancialAcc(fa);
        
        
 
        
        if(IntlRadioButton3.isSelected())
        {
       LicenseTypeTxtfield.setText(IntlRadioButton3.getText());
        }
        else if (NationalRadioButton2.isSelected())
        {
           LicenseTypeTxtfield.setText(NationalRadioButton2.getText()); 
        }
        else
        {
                LicenseTypeTxtfield.setText(null);
                }
        
        JOptionPane.showMessageDialog(null,"Information Submited successfully");
       
    }//GEN-LAST:event_createbuttonActionPerformed

    private void IntlRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntlRadioButton3ActionPerformed
        // TO SELECT THE TYPE OF LICENSE AS INTERNATIONAL
        
       LicenseTypeTxtfield.setText(IntlRadioButton3.getText());
    }//GEN-LAST:event_IntlRadioButton3ActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        
       fnameTxtfield.setText(" ");
       lnameTxtField.setText(" ");
       dobTxtField.setText(" ");
       ssnTxtField.setText(" ");
       addLine1Txtfield.setText(" ");
       add2TxtField.setText(" ");
       cityTxtfield.setText(" ");
       countryTxtfield.setText(" ");
       ZipcodeTxtField.setText(" ");
       LicenseTypeTxtfield.setText(" ");
       issueDateTxtfield1.setText(" ");
       ExpDateTxtfield.setText(" ");
       LicenenumTxtfield.setText(" ");
       StateLicenseIssuedTxtfield.setText(" ");
       BnkcadnumTxtfield.setText(" ");
       bnkexpDateTxtfield.setText(" ");
       bnkissueDateTxtfield.setText(" ");
       lscissueDateTxtfield.setText(" ");
       NameoncardTxtfield.setText(" ");
       AcctypeTextField.setText(" ");
       FAbnknameTxtfield.setText(" ");
       FABnkAddTxtfield.setText(" ");
       AccStatusTxtField.setText(" ");
       BalanceStatusTxtfield.setText(" ");
       natinternationalgrp.clearSelection();
       activeinactivegrp.clearSelection();
       debtcreditgrp.clearSelection();
       checkingsavinggrp.clearSelection();
       imagejTextField.setText(" ");
       imagejLabel.setIcon(null);
       
       JOptionPane.showMessageDialog(null,"Entered Information cleared. Please re-enter the details carefully.");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void debtRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debtRadioButtonActionPerformed
        // TODO add your handling code here:
        
        BalanceStatusTxtfield.setText(debtRadioButton.getText());
    }//GEN-LAST:event_debtRadioButtonActionPerformed

    private void NationalRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalRadioButton2ActionPerformed
        // TO SELECT THE TYPE OF LICENSE AS NATIONAL 
        //NationalRadioButton2.setSelected(false);
        LicenseTypeTxtfield.setText(NationalRadioButton2.getText());
        
        
    }//GEN-LAST:event_NationalRadioButton2ActionPerformed

    private void AcctypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcctypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcctypeTextFieldActionPerformed

    private void AttachjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachjButtonActionPerformed
        // TO INSERT AN IMAGE
        
    JOptionPane.showMessageDialog(null,"Please attach your most recent photo. Accepted formats .jpg,.png, .jpeg");
    JFileChooser chooser=new JFileChooser();
    chooser.showOpenDialog(null);
    File f=chooser.getSelectedFile();
    String filename=f.getAbsolutePath();
    imagejTextField.setText(filename); 
    ImageIcon icon=new ImageIcon(filename);
    imagejLabel.setIcon(icon);
    customer.setPathname(filename);
    
    JOptionPane.showMessageDialog(null,"Photo Attached successfully. Please view the image and click 'Attach' to affix a new image.");
   
    }//GEN-LAST:event_AttachjButtonActionPerformed

    private void ActiveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActiveRadioButtonActionPerformed
        // TO SELECT THE ACC STATUS
        
        AccStatusTxtField.setText(ActiveRadioButton.getText());
    }//GEN-LAST:event_ActiveRadioButtonActionPerformed

    private void inactiveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inactiveRadioButtonActionPerformed
        // TO SELECT THE ACC STATUS INACTIVE FLAG
        
        AccStatusTxtField.setText(inactiveRadioButton.getText());
    }//GEN-LAST:event_inactiveRadioButtonActionPerformed

    private void creditRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditRadioButtonActionPerformed
        // TODO add your handling code here:
        
        BalanceStatusTxtfield.setText(creditRadioButton.getText());
    }//GEN-LAST:event_creditRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccLabel;
    private javax.swing.JTextField AccStatusTxtField;
    private javax.swing.JLabel AcctypeLAbel;
    private javax.swing.JTextField AcctypeTextField;
    private javax.swing.JRadioButton ActiveRadioButton;
    private javax.swing.JLabel Addresslabel;
    private javax.swing.JButton AttachjButton;
    private javax.swing.JLabel BalanceStatus;
    private javax.swing.JTextField BalanceStatusTxtfield;
    private javax.swing.JLabel BankNameLabel;
    private javax.swing.JLabel BankNameLabel2;
    private javax.swing.JLabel BankNameLabel3;
    private javax.swing.JLabel BankNameLabel4;
    private javax.swing.JLabel BkissuedateLabel;
    private javax.swing.JTextField BnkcadnumTxtfield;
    private javax.swing.JTextField ExpDateTxtfield;
    private javax.swing.JLabel FABankAddLabel;
    private javax.swing.JLabel FABankNameLabel;
    private javax.swing.JTextField FABnkAddTxtfield;
    private javax.swing.JTextField FAbnknameTxtfield;
    private javax.swing.JLabel FAbnkstatusLabel;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Fname1;
    private javax.swing.JLabel Fname2;
    private javax.swing.JLabel Fname3;
    private javax.swing.JLabel Heading;
    private javax.swing.JRadioButton IntlRadioButton3;
    private javax.swing.JTextField LicenenumTxtfield;
    private javax.swing.JLabel LicenseExpDateLabel1;
    private javax.swing.JLabel LicenseIssueDateLabel1;
    private javax.swing.JLabel LicenseStateIssuedLabel1;
    private javax.swing.JTextField LicenseTypeTxtfield;
    private javax.swing.JLabel Licenselabel1;
    private javax.swing.JLabel LicensenumLabel1;
    private javax.swing.JTextField NameoncardTxtfield;
    private javax.swing.JRadioButton NationalRadioButton2;
    private javax.swing.JRadioButton SavingaccRadioButton;
    private javax.swing.JTextField StateLicenseIssuedTxtfield;
    private javax.swing.JTextField ZipcodeTxtField;
    private javax.swing.ButtonGroup activeinactivegrp;
    private javax.swing.JTextField add2TxtField;
    private javax.swing.JLabel addLine1;
    private javax.swing.JTextField addLine1Txtfield;
    private javax.swing.JLabel addLine2;
    private javax.swing.JTextField bnkexpDateTxtfield;
    private javax.swing.JTextField bnkissueDateTxtfield;
    private javax.swing.JRadioButton checkingAccRadioButton;
    private javax.swing.ButtonGroup checkingsavinggrp;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTxtfield;
    private javax.swing.JButton clearbutton;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTxtfield;
    private javax.swing.JButton createbutton;
    private javax.swing.JLabel creditCardLabel1;
    private javax.swing.JRadioButton creditRadioButton;
    private javax.swing.JRadioButton debtRadioButton;
    private javax.swing.ButtonGroup debtcreditgrp;
    private javax.swing.JTextField dobTxtField;
    private javax.swing.JTextField fnameTxtfield;
    private javax.swing.JLabel imagejLabel;
    private javax.swing.JTextField imagejTextField;
    private javax.swing.JRadioButton inactiveRadioButton;
    private javax.swing.JTextField issueDateTxtfield1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel licenseTypeLabel1;
    private javax.swing.JTextField lnameTxtField;
    private javax.swing.JTextField lscissueDateTxtfield;
    private javax.swing.ButtonGroup natinternationalgrp;
    private javax.swing.JLabel personalDetails;
    private javax.swing.JTextField ssnTxtField;
    private javax.swing.JLabel ziplabel;
    // End of variables declaration//GEN-END:variables

    
}
