/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustInterface;
import CustDetails.*; 
import java.awt.Image;
import java.io.File;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author Rohan
 */

public class ViewCust extends javax.swing.JPanel {

    /**
     * Creates new form ViewCust
     */
    private Customer customer;
    public ViewCust(Customer customer) {
        initComponents();
        displayCustomerDetails(customer);
    }
    private void displayCustomerDetails (Customer customer){
     
        String CustomerFirstName=customer.getFirstname();
        fnameTxtField.setText(CustomerFirstName);
        
        String CustomerLastName=customer.getLastname();
        lnameTxtField.setText(CustomerLastName);
        
        //Date CustomerDob=customer.getDob();
        //SimpleDateFormat sf = new SimpleDateFormat("mm-dd-yy"); 
        //dobTxtField.setText(sf.format(CustomerDob));
        //dobTxtField.setText(date.tostring(CustomerDob));
        String ssn = Integer.toString(customer.getSsn());
        //CountryTxtfield.setText(ctf);
        //String CustomerSSN=customer.getSsn();
        ssnTxtField.setText(ssn);
        String dateOfBirth =customer.getDob();
        dobTxtField.setText(dateOfBirth);
        
        addLine1Txtfield.setText(customer.getAdd().getAddline1());
        add2TxtField.setText(customer.getAdd().getAddline2());
        cityTxtfield.setText(customer.getAdd().getCity());
        countryTxtfield.setText(customer.getAdd().getCountry());
        String ctf = Integer.toString(customer.getAdd().getZipcode());
        ZipcodeTxtField.setText(ctf);
        
        LicenseTypeTxtfield.setText(customer.getLicenseDetails().getLicenseType());
        issueDateTxtfield.setText(customer.getLicenseDetails().getIssueDate());
        ExpDateTxtfield.setText(customer.getLicenseDetails().getExpDate());       
        String lno=Integer.toString(customer.getLicenseDetails().getLicenseNum());
        LicenenumTxtfield.setText(lno);
        StateLicenseIssuedTxtfield.setText(customer.getLicenseDetails().getStatelicenseIssued());
        issueDateTxtfield1.setText(customer.getCreditCard().getExpDate());
        
        String cd=Integer.toString(customer.getCreditCard().getCardNum());
        BnkcadnumTxtfield.setText(cd);
        //BnkcadnumTxtfield.setText(customer.getCreditCard().getCardNum());
        bnkexpDateTxtfield.setText(customer.getCreditCard().getExpDate());
        bnkissueDateTxtfield.setText(customer.getCreditCard().getIssueDate());
        NameoncardTxtfield.setText(customer.getCreditCard().getNameOnCard());
        
        AcctypeTextField.setText(customer.getFinancialAcc().getAccType());
        FAbnknameTxtfield.setText(customer.getFinancialAcc().getBnkName());
        FABnkAddTxtfield.setText(customer.getFinancialAcc().getBnkAdd());
        AccStatusTxtField.setText(customer.getFinancialAcc().getStatus());
        BalanceStatusTxtfield.setText(customer.getFinancialAcc().getBalanceStatus());
        
        
       String filename = customer.getPathname();
       ImageIcon icon=new ImageIcon(filename);
       imagejLabel.setIcon(icon);
        
       //JFileChooser chooser=new JFileChooser();
   // chooser.showOpenDialog(null);
  //  File f=chooser.getSelectedFile();
   // String filename=f.getAbsolutePath();
   // imagejTextField.setText(filename); 
   // ImageIcon icon=new ImageIcon(filename);
  //  imagejLabel.setIcon(icon);
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        personalDetails = new javax.swing.JLabel();
        Fname1 = new javax.swing.JLabel();
        Fname2 = new javax.swing.JLabel();
        lnameTxtField = new javax.swing.JTextField();
        Fname3 = new javax.swing.JLabel();
        dobTxtField = new javax.swing.JTextField();
        Fname = new javax.swing.JLabel();
        ssnTxtField = new javax.swing.JTextField();
        Addresslabel = new javax.swing.JLabel();
        addLine1 = new javax.swing.JLabel();
        addLine1Txtfield = new javax.swing.JTextField();
        addLine2 = new javax.swing.JLabel();
        fnameTxtField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTxtfield = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        countryTxtfield = new javax.swing.JTextField();
        ziplabel = new javax.swing.JLabel();
        Licenselabel1 = new javax.swing.JLabel();
        licenseTypeLabel1 = new javax.swing.JLabel();
        LicenseIssueDateLabel1 = new javax.swing.JLabel();
        LicenseExpDateLabel1 = new javax.swing.JLabel();
        issueDateTxtfield = new javax.swing.JTextField();
        ExpDateTxtfield = new javax.swing.JTextField();
        LicenenumTxtfield = new javax.swing.JTextField();
        LicensenumLabel1 = new javax.swing.JLabel();
        LicenseStateIssuedLabel1 = new javax.swing.JLabel();
        StateLicenseIssuedTxtfield = new javax.swing.JTextField();
        creditCardLabel1 = new javax.swing.JLabel();
        BankNameLabel = new javax.swing.JLabel();
        issueDateTxtfield1 = new javax.swing.JTextField();
        BkissuedateLabel = new javax.swing.JLabel();
        bnkissueDateTxtfield = new javax.swing.JTextField();
        BankNameLabel2 = new javax.swing.JLabel();
        bnkexpDateTxtfield = new javax.swing.JTextField();
        BankNameLabel3 = new javax.swing.JLabel();
        BnkcadnumTxtfield = new javax.swing.JTextField();
        BankNameLabel4 = new javax.swing.JLabel();
        NameoncardTxtfield = new javax.swing.JTextField();
        AccLabel = new javax.swing.JLabel();
        AcctypeLAbel = new javax.swing.JLabel();
        checkingAccRadioButton = new javax.swing.JRadioButton();
        SavingaccRadioButton = new javax.swing.JRadioButton();
        FABankNameLabel = new javax.swing.JLabel();
        FAbnknameTxtfield = new javax.swing.JTextField();
        FABankAddLabel = new javax.swing.JLabel();
        FABnkAddTxtfield = new javax.swing.JTextField();
        FAbnkstatusLabel = new javax.swing.JLabel();
        ActiveRadioButton = new javax.swing.JRadioButton();
        inactiveRadioButton = new javax.swing.JRadioButton();
        add2TxtField = new javax.swing.JTextField();
        NationalRadioButton2 = new javax.swing.JRadioButton();
        IntlRadioButton3 = new javax.swing.JRadioButton();
        debtRadioButton = new javax.swing.JRadioButton();
        creditRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        LicenseTypeTxtfield = new javax.swing.JTextField();
        AcctypeTextField = new javax.swing.JTextField();
        AccStatusTxtField = new javax.swing.JTextField();
        BalanceStatusTxtfield = new javax.swing.JTextField();
        imagejLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ZipcodeTxtField = new javax.swing.JTextField();

        Heading.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Heading.setText("     View Customer Details");

        personalDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        personalDetails.setText("Personal Details");

        Fname1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Fname1.setText("First Name:");

        Fname2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Fname2.setText("Last Name:");

        Fname3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Fname3.setText("Date Of Birth:");

        Fname.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Fname.setText("Social Security Number:");

        ssnTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnTxtFieldActionPerformed(evt);
            }
        });

        Addresslabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Addresslabel.setText("Address");

        addLine1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        addLine1.setText("Address Line 1:");

        addLine2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        addLine2.setText("Address Line 2:");

        cityLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cityLabel.setText("City:");

        countryLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        countryLabel.setText("Country:");

        ziplabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ziplabel.setText("Zipcode:");

        Licenselabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Licenselabel1.setText("License Data");

        licenseTypeLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        licenseTypeLabel1.setText("License Type:");

        LicenseIssueDateLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LicenseIssueDateLabel1.setText("Issue Date:");

        LicenseExpDateLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LicenseExpDateLabel1.setText("Expiry Date:");

        issueDateTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueDateTxtfieldActionPerformed(evt);
            }
        });

        ExpDateTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpDateTxtfieldActionPerformed(evt);
            }
        });

        LicensenumLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LicensenumLabel1.setText("License No.:");

        LicenseStateIssuedLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LicenseStateIssuedLabel1.setText("State License Issued:");

        creditCardLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        creditCardLabel1.setText("Credit Card Details");

        BankNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BankNameLabel.setText("Bank Name:");

        issueDateTxtfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueDateTxtfield1ActionPerformed(evt);
            }
        });

        BkissuedateLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BkissuedateLabel.setText("Issue Date:");

        bnkissueDateTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnkissueDateTxtfieldActionPerformed(evt);
            }
        });

        BankNameLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BankNameLabel2.setText("Expiry Date:");

        bnkexpDateTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnkexpDateTxtfieldActionPerformed(evt);
            }
        });

        BankNameLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BankNameLabel3.setText("Card No.:");

        BnkcadnumTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnkcadnumTxtfieldActionPerformed(evt);
            }
        });

        BankNameLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BankNameLabel4.setText("Name on the card:");

        NameoncardTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameoncardTxtfieldActionPerformed(evt);
            }
        });

        AccLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AccLabel.setText("Financial Account Details");

        AcctypeLAbel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        AcctypeLAbel.setText("Account Type:");

        checkingAccRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        checkingAccRadioButton.setText("Checking Account");
        checkingAccRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingAccRadioButtonActionPerformed(evt);
            }
        });

        SavingaccRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        SavingaccRadioButton.setText("Saving Account");
        SavingaccRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingaccRadioButtonActionPerformed(evt);
            }
        });

        FABankNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FABankNameLabel.setText("Bank Name:");

        FAbnknameTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAbnknameTxtfieldActionPerformed(evt);
            }
        });

        FABankAddLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FABankAddLabel.setText("Bank Address:");

        FABnkAddTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FABnkAddTxtfieldActionPerformed(evt);
            }
        });

        FAbnkstatusLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FAbnkstatusLabel.setText("Status:");

        ActiveRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ActiveRadioButton.setText("Active");

        inactiveRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        inactiveRadioButton.setText("Inactive");

        NationalRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        NationalRadioButton2.setText("National");
        NationalRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationalRadioButton2ActionPerformed(evt);
            }
        });

        IntlRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        IntlRadioButton3.setText("International");
        IntlRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntlRadioButton3ActionPerformed(evt);
            }
        });

        debtRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        debtRadioButton.setText("Debt");
        debtRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debtRadioButtonActionPerformed(evt);
            }
        });

        creditRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        creditRadioButton.setText("Credit");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Balance Status");

        LicenseTypeTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicenseTypeTxtfieldActionPerformed(evt);
            }
        });

        imagejLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        imagejLabel.setText("                 Affix Image Here");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(197, 197, 197)
                                    .addComponent(cityTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(addLine2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(add2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(addLine1)
                                    .addGap(130, 130, 130)
                                    .addComponent(addLine1Txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ssnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Fname3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(131, 131, 131)
                                        .addComponent(dobTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(personalDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(Fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(149, 149, 149)
                                            .addComponent(fnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(Fname2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(149, 149, 149)
                                            .addComponent(lnameTxtField))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(countryTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(414, 414, 414)
                                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BankNameLabel4)
                                    .addComponent(AcctypeLAbel)
                                    .addComponent(FABankNameLabel)
                                    .addComponent(FABankAddLabel)
                                    .addComponent(FAbnkstatusLabel)
                                    .addComponent(jLabel1))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameoncardTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FAbnknameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(checkingAccRadioButton)
                                                .addGap(37, 37, 37)
                                                .addComponent(SavingaccRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(FABnkAddTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ActiveRadioButton)
                                                    .addComponent(debtRadioButton))
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(creditRadioButton)
                                                    .addComponent(inactiveRadioButton))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AcctypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                            .addComponent(AccStatusTxtField)
                                            .addComponent(BalanceStatusTxtfield)))
                                    .addComponent(BnkcadnumTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(765, 765, 765)
                                .addComponent(LicenseTypeTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Licenselabel1)
                            .addComponent(BankNameLabel3)
                            .addComponent(BankNameLabel)
                            .addComponent(LicenseStateIssuedLabel1)
                            .addComponent(LicenseExpDateLabel1)
                            .addComponent(creditCardLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(LicenseIssueDateLabel1)
                                                .addGap(170, 170, 170))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(licenseTypeLabel1)
                                                .addGap(141, 141, 141))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(LicensenumLabel1)
                                                .addGap(155, 155, 155)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(BkissuedateLabel)
                                            .addGap(170, 170, 170)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BankNameLabel2)
                                        .addGap(154, 154, 154)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bnkexpDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bnkissueDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LicenenumTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NationalRadioButton2)
                                        .addGap(50, 50, 50)
                                        .addComponent(IntlRadioButton3))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ExpDateTxtfield, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                        .addComponent(issueDateTxtfield))
                                    .addComponent(StateLicenseIssuedTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(issueDateTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ziplabel)
                                .addGap(198, 198, 198)
                                .addComponent(ZipcodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(personalDetails)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fname2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dobTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fname3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fname)
                            .addComponent(ssnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Addresslabel)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addLine1)
                            .addComponent(addLine1Txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addLine2)
                            .addComponent(add2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cityTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(imagejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countryTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ziplabel)
                            .addComponent(ZipcodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(Licenselabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenseTypeLabel1)
                            .addComponent(NationalRadioButton2)
                            .addComponent(IntlRadioButton3)
                            .addComponent(LicenseTypeTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issueDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LicenseIssueDateLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LicenseExpDateLabel1)
                            .addComponent(ExpDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LicenenumTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LicensenumLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LicenseStateIssuedLabel1)
                            .addComponent(StateLicenseIssuedTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditCardLabel1)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BankNameLabel)
                            .addComponent(issueDateTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BkissuedateLabel)
                            .addComponent(bnkissueDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BankNameLabel2)
                            .addComponent(bnkexpDateTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BankNameLabel3)
                            .addComponent(BnkcadnumTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameoncardTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BankNameLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AcctypeLAbel)
                            .addComponent(checkingAccRadioButton)
                            .addComponent(SavingaccRadioButton)
                            .addComponent(AcctypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FAbnknameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(FABankNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FABankAddLabel)
                            .addComponent(FABnkAddTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FAbnkstatusLabel)
                            .addComponent(ActiveRadioButton)
                            .addComponent(inactiveRadioButton)
                            .addComponent(AccStatusTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(debtRadioButton)
                            .addComponent(creditRadioButton)
                            .addComponent(BalanceStatusTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LicenseTypeTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicenseTypeTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicenseTypeTxtfieldActionPerformed

    private void debtRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debtRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debtRadioButtonActionPerformed

    private void IntlRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntlRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntlRadioButton3ActionPerformed

    private void FABnkAddTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FABnkAddTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FABnkAddTxtfieldActionPerformed

    private void FAbnknameTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAbnknameTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FAbnknameTxtfieldActionPerformed

    private void SavingaccRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingaccRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavingaccRadioButtonActionPerformed

    private void checkingAccRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingAccRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingAccRadioButtonActionPerformed

    private void NameoncardTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameoncardTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameoncardTxtfieldActionPerformed

    private void BnkcadnumTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnkcadnumTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BnkcadnumTxtfieldActionPerformed

    private void bnkexpDateTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnkexpDateTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnkexpDateTxtfieldActionPerformed

    private void bnkissueDateTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnkissueDateTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnkissueDateTxtfieldActionPerformed

    private void issueDateTxtfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueDateTxtfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueDateTxtfield1ActionPerformed

    private void ExpDateTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpDateTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpDateTxtfieldActionPerformed

    private void issueDateTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueDateTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueDateTxtfieldActionPerformed

    private void ssnTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnTxtFieldActionPerformed

    private void NationalRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationalRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccLabel;
    private javax.swing.JTextField AccStatusTxtField;
    private javax.swing.JLabel AcctypeLAbel;
    private javax.swing.JTextField AcctypeTextField;
    private javax.swing.JRadioButton ActiveRadioButton;
    private javax.swing.JLabel Addresslabel;
    private javax.swing.JTextField BalanceStatusTxtfield;
    private javax.swing.JLabel BankNameLabel;
    private javax.swing.JLabel BankNameLabel2;
    private javax.swing.JLabel BankNameLabel3;
    private javax.swing.JLabel BankNameLabel4;
    private javax.swing.JLabel BkissuedateLabel;
    private javax.swing.JTextField BnkcadnumTxtfield;
    private javax.swing.JTextField ExpDateTxtfield;
    private javax.swing.JLabel FABankAddLabel;
    private javax.swing.JLabel FABankNameLabel;
    private javax.swing.JTextField FABnkAddTxtfield;
    private javax.swing.JTextField FAbnknameTxtfield;
    private javax.swing.JLabel FAbnkstatusLabel;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Fname1;
    private javax.swing.JLabel Fname2;
    private javax.swing.JLabel Fname3;
    private javax.swing.JLabel Heading;
    private javax.swing.JRadioButton IntlRadioButton3;
    private javax.swing.JTextField LicenenumTxtfield;
    private javax.swing.JLabel LicenseExpDateLabel1;
    private javax.swing.JLabel LicenseIssueDateLabel1;
    private javax.swing.JLabel LicenseStateIssuedLabel1;
    private javax.swing.JTextField LicenseTypeTxtfield;
    private javax.swing.JLabel Licenselabel1;
    private javax.swing.JLabel LicensenumLabel1;
    private javax.swing.JTextField NameoncardTxtfield;
    private javax.swing.JRadioButton NationalRadioButton2;
    private javax.swing.JRadioButton SavingaccRadioButton;
    private javax.swing.JTextField StateLicenseIssuedTxtfield;
    private javax.swing.JTextField ZipcodeTxtField;
    private javax.swing.JTextField add2TxtField;
    private javax.swing.JLabel addLine1;
    private javax.swing.JTextField addLine1Txtfield;
    private javax.swing.JLabel addLine2;
    private javax.swing.JTextField bnkexpDateTxtfield;
    private javax.swing.JTextField bnkissueDateTxtfield;
    private javax.swing.JRadioButton checkingAccRadioButton;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTxtfield;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTxtfield;
    private javax.swing.JLabel creditCardLabel1;
    private javax.swing.JRadioButton creditRadioButton;
    private javax.swing.JRadioButton debtRadioButton;
    private javax.swing.JTextField dobTxtField;
    private javax.swing.JTextField fnameTxtField;
    private javax.swing.JLabel imagejLabel;
    private javax.swing.JRadioButton inactiveRadioButton;
    private javax.swing.JTextField issueDateTxtfield;
    private javax.swing.JTextField issueDateTxtfield1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel licenseTypeLabel1;
    private javax.swing.JTextField lnameTxtField;
    private javax.swing.JLabel personalDetails;
    private javax.swing.JTextField ssnTxtField;
    private javax.swing.JLabel ziplabel;
    // End of variables declaration//GEN-END:variables
}
