/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.manageCust;

import Business.Flight;
import Business.FlightSchedule;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohan
 */
public class searchCustJPanel extends javax.swing.JPanel {
private JPanel UserProcessContainer;
private FlightSchedule flightSch;
private String anumber, anumber1, anumber2, anumber3;
private int anumber4;
    /**
     * Creates new form searchCustJPanel
     */


   public searchCustJPanel(JPanel UserProcessContainer, FlightSchedule flightSch) {
        initComponents();
         this.flightSch = flightSch ;
         this.UserProcessContainer = UserProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fromjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DestinationjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        morningjRadioButton = new javax.swing.JRadioButton();
        EveningjRadioButton = new javax.swing.JRadioButton();
        NightjRadioButton = new javax.swing.JRadioButton();
        serachflightpreferjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        preferdisplayjTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        airlinerpreferjTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        slotsjTextField = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter flight preferences");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Source:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Destination:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Select the prefered time slots:");

        morningjRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        morningjRadioButton.setText("Morning");
        morningjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morningjRadioButtonActionPerformed(evt);
            }
        });

        EveningjRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        EveningjRadioButton.setText("Evening");
        EveningjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EveningjRadioButtonActionPerformed(evt);
            }
        });

        NightjRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        NightjRadioButton.setText("Night");
        NightjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NightjRadioButtonActionPerformed(evt);
            }
        });

        serachflightpreferjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        serachflightpreferjButton.setText("Search");
        serachflightpreferjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachflightpreferjButtonActionPerformed(evt);
            }
        });

        preferdisplayjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Source", "Destination", "Time", "Price (in Dollars)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(preferdisplayjTable);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Airliner:");

        airlinerpreferjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerpreferjTextFieldActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(320, 320, 320))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel2))
                                            .addGap(102, 102, 102)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(airlinerpreferjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fromjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(DestinationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(147, 147, 147))
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(morningjRadioButton)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(serachflightpreferjButton)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(EveningjRadioButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(NightjRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(slotsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(airlinerpreferjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fromjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DestinationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(morningjRadioButton)
                    .addComponent(EveningjRadioButton)
                    .addComponent(NightjRadioButton)
                    .addComponent(slotsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(serachflightpreferjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EveningjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EveningjRadioButtonActionPerformed
        // TODO add your handling code here:
        slotsjTextField.setText(EveningjRadioButton.getText());
    }//GEN-LAST:event_EveningjRadioButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void serachflightpreferjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachflightpreferjButtonActionPerformed
        // TODO add your handling code here:
       int  k=0;
        System.out.println("search");
        try
        {
            System.out.println("in try");
            anumber = airlinerpreferjTextField.getText();
            anumber1 = fromjTextField.getText();
            anumber2 = DestinationjTextField.getText();
            anumber3 = slotsjTextField.getText();
            System.out.println(anumber);
        }
        catch(Exception e)
        {
            System.out.println("Some Exception");
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, "Plese enter correct values");
            //i = 1;
        }
        //System.out.println(ad.getAirplaneDirectory().size());
              
        
        
        
        for (Flight f : flightSch.getFlightCollection())
        {
            System.out.println("In for");
          Object data[] = new Object[5];
        
        //String x = ap.getFlightNumber();
        if(anumber.equalsIgnoreCase(f.getFlightName())&& anumber1.equalsIgnoreCase(f.getArrival())&& anumber2.equalsIgnoreCase(f.getDepart())&&anumber3.equalsIgnoreCase(f.getTimestamp()))
        {
            k=1;
        data[0] = f.getFlightName();
        data[1] = f.getArrival();
        data[2] = f.getDepart();
        data[3] = f.getTimestamp();
        data[4] = f.getPrice();
       // data[3] = ap.getAirportName();
        DefaultTableModel dm = (DefaultTableModel)preferdisplayjTable.getModel();
        //dm.setRowCount(0);
        dm.addRow(data);
        }
        }
        if(k==0)
        {
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, "Invalid Input. Plese enter correct values");
        }                                                 

    }//GEN-LAST:event_serachflightpreferjButtonActionPerformed

    private void morningjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morningjRadioButtonActionPerformed
        // TODO add your handling code here:
        slotsjTextField.setText(morningjRadioButton.getText());
    }//GEN-LAST:event_morningjRadioButtonActionPerformed

    private void NightjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NightjRadioButtonActionPerformed
        // TODO add your handling code here:
        slotsjTextField.setText(NightjRadioButton.getText());
    }//GEN-LAST:event_NightjRadioButtonActionPerformed

    private void airlinerpreferjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerpreferjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlinerpreferjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DestinationjTextField;
    private javax.swing.JRadioButton EveningjRadioButton;
    private javax.swing.JRadioButton NightjRadioButton;
    private javax.swing.JTextField airlinerpreferjTextField;
    private javax.swing.JTextField fromjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton morningjRadioButton;
    private javax.swing.JTable preferdisplayjTable;
    private javax.swing.JButton serachflightpreferjButton;
    private javax.swing.JTextField slotsjTextField;
    // End of variables declaration//GEN-END:variables
}
