/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.manageCust;

import Business.CustomerDirectory;
import Business.Flight;
import Business.FlightSchedule;
import Business.Person;
import Business.SeatDirectory;
import Business.Seats;
import java.awt.CardLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohan
 */
public class singleTicketJPanel extends javax.swing.JPanel {
private JPanel UserProcessContainer;
private FlightSchedule flightSch;
private SeatDirectory sd;
private CustomerDirectory cd;
private String anumber, anumber1, anumber2, anumber3, anumber4;
    /**
     * Creates new form singleTicketJPanel
     */


   public singleTicketJPanel(JPanel UserProcessContainer, FlightSchedule flightSch) {
        initComponents();
        this.cd = cd;
        this.flightSch = flightSch;
         this.sd = sd ;
         this.UserProcessContainer = UserProcessContainer;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sourcejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        destinationjTextField = new javax.swing.JTextField();
        searchjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookjTable = new javax.swing.JTable();
        bookjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fnamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lnamejTextField1 = new javax.swing.JTextField();
        backjButton = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        jLabel1.setText("Enter Details");

        jLabel4.setText("Source:");

        jLabel5.setText("Destination:");

        destinationjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationjTextFieldActionPerformed(evt);
            }
        });

        searchjButton.setText("Search");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        bookjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Source", "Destination", "Price(in Dollars)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookjTable);

        bookjButton.setText("Book");
        bookjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        backjButton.setText("<< Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(402, 402, 402)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(302, 302, 302)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sourcejTextField)
                                        .addComponent(destinationjTextField)
                                        .addComponent(searchjButton)
                                        .addComponent(fnamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                        .addComponent(lnamejTextField1))))
                            .addGap(159, 159, 159))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(bookjButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backjButton)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 175, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lnamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sourcejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(destinationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(searchjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(backjButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void destinationjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationjTextFieldActionPerformed

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        // TODO add your handling code here:
         int  k=0;
        System.out.println("search");
        try
        {
            System.out.println("in try");
            anumber = sourcejTextField.getText();
            anumber1 = destinationjTextField.getText();
            anumber2 = fnamejTextField.getText();
            anumber3 = lnamejTextField1.getText();
            System.out.println(anumber);
        }
        catch(Exception e)
        {
            System.out.println("Some Exception");
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, "Plese enter correct values");
            //i = 1;
        }
        //System.out.println(ad.getAirplaneDirectory().size());
              
        
        
        
        for (Flight f : flightSch.getFlightCollection())
        {
            System.out.println("In for");
          Object data[] = new Object[5];
        
        //String x = ap.getFlightNumber();
        if(anumber.equalsIgnoreCase(f.getArrival())&& anumber1.equalsIgnoreCase(f.getDepart()))
        {
            k=1;
        data[0] = f;
        data[1] = f.getArrival();
        data[2] = f.getDepart();
        data[3] = f.getPrice();
       // data[3] = ap.getAirportName();
        DefaultTableModel dm = (DefaultTableModel)bookjTable.getModel();
        //dm.setRowCount(0);
        dm.addRow(data);
        }
        }
        if(k==0)
        {
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, "Invalid Input. Plese enter correct values");
        }                                                 

     
                                                             
        
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void bookjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookjButtonActionPerformed
        // TODO add your handling code here:
        int selectedrow = bookjTable.getSelectedRow();
        if (selectedrow >= 0)
        {
            Flight f = (Flight) bookjTable.getValueAt(selectedrow,0);
            int cfr = JOptionPane.showConfirmDialog(null, "Are you sure to book");
            if (cfr == 0)
            {
            Random r = new Random();
            char c = (char)(r.nextInt(5) + 'a');
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, anumber2 +" " + anumber3+ "  your ticket has been booked. Your seat number is:  " + ThreadLocalRandom.current().nextInt(1, 100+1)+c );
            }
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null,"We wish you a happy journey..!!");
            
        }
        
        
        
    }//GEN-LAST:event_bookjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
                UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JButton bookjButton;
    private javax.swing.JTable bookjTable;
    private javax.swing.JTextField destinationjTextField;
    private javax.swing.JTextField fnamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnamejTextField1;
    private javax.swing.JButton searchjButton;
    private javax.swing.JTextField sourcejTextField;
    // End of variables declaration//GEN-END:variables
}
