/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Supplier;

import Business.Business;
import Business.Market;
import Business.MarketOffer;
import Business.OrderItem;
import Business.Product;
import Business.ProductCatalog;
import Business.Suppliers;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanaj
 */
public class MarketOfferJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MarketOfferJPanel
     */
    private JPanel userProcessContainer;
    private Suppliers supplier;
    private Business business;
    private ProductCatalog productCatalog;

    public MarketOfferJPanel(JPanel userProcessContainer, Business business, Suppliers supplier) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.productCatalog = supplier.getProductCatalog();

        selectProductDropDown.removeAllItems();;
        for (Product product : productCatalog.getProductCatalog()) {
            selectProductDropDown.addItem(product);
        }

        selectMarketDropDown.removeAllItems();
        for (Market market : business.getMarketList()) {
            selectMarketDropDown.addItem(market);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectProductDropDown = new javax.swing.JComboBox<>();
        selectMarketDropDown = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        selectMarket = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        targetPriceTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        marketOfferJTable = new javax.swing.JTable();
        goBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        floorPriceMarketOfferTextField = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        ceilingPriceMarketOfferTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectProductDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProductDropDownActionPerformed(evt);
            }
        });
        add(selectProductDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 178, 125, 36));

        add(selectMarketDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 177, 137, 38));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT PRODUCT");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 175, 167, 42));

        selectMarket.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        selectMarket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectMarket.setText("SELECT MARKET");
        selectMarket.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(selectMarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 175, 157, 42));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TARGET PRICE");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 270, 180, 45));
        add(targetPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 145, 45));

        marketOfferJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductName", "Market", "Floor Price", "Target Price", "Ceiling Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(marketOfferJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 660, 150));

        goBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        goBtn.setText("GO >>");
        goBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        goBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnActionPerformed(evt);
            }
        });
        add(goBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 77, 52));

        backBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backBtn.setText(" << BACK");
        backBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 810, 170, 51));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MARKET OFFER");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 29, 830, 90));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FLOOR PRICE:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 190, 45));
        add(floorPriceMarketOfferTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 150, 40));

        label.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("CEILING PRICE:");
        label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 190, 45));
        add(ceilingPriceMarketOfferTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void selectProductDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProductDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectProductDropDownActionPerformed

    private void goBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnActionPerformed
        // TODO add your handling code here:
        MarketOffer marketOffer = new MarketOffer();
        marketOffer.setProduct((Product)selectProductDropDown.getSelectedItem());
        marketOffer.setMarket((Market)selectMarketDropDown.getSelectedItem());
        marketOffer.setMarketOfferPrice(Integer.parseInt(targetPriceTextField.getText()));
        marketOffer.setFloorPrice(Integer.parseInt(floorPriceMarketOfferTextField.getText()));
        marketOffer.setCeilingPrice(Integer.parseInt(ceilingPriceMarketOfferTextField.getText()));
        
        business.getMarketOfferCatalog().getMarketOfferList().add(marketOffer);
        
        DefaultTableModel model = (DefaultTableModel) marketOfferJTable.getModel();
        model.setRowCount(0);
        for (MarketOffer marketOfferObject : business.getMarketOfferCatalog().getMarketOfferList()) {

            Object row[] = new Object[5];
            row[0] = marketOfferObject.getProduct().getProdname();
            row[1] = marketOfferObject.getMarket().getMarketName();
            row[2] = marketOfferObject.getFloorPrice();
            row[3] = marketOfferObject.getMarketOfferPrice();
            row[4] = marketOfferObject.getCeilingPrice();
            model.addRow(row);

        }
    }//GEN-LAST:event_goBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField ceilingPriceMarketOfferTextField;
    private javax.swing.JTextField floorPriceMarketOfferTextField;
    private javax.swing.JButton goBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTable marketOfferJTable;
    private javax.swing.JLabel selectMarket;
    private javax.swing.JComboBox<Market> selectMarketDropDown;
    private javax.swing.JComboBox<Product> selectProductDropDown;
    private javax.swing.JTextField targetPriceTextField;
    // End of variables declaration//GEN-END:variables
}
