/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airplane;
import Business.AirplaneDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohan
 */
public class AirportNameJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AirportNameJPanel
     */
    private AirplaneDirectory ad;
    private Airplane ap;
    private String anumber;
    public AirportNameJPanel(AirplaneDirectory ad) {
        initComponents();
        this.ad = ad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AirportnamejTextField = new javax.swing.JTextField();
        searchaiportnamejButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        airportnamejTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter the Airport Name:");

        searchaiportnamejButton.setText("Search");
        searchaiportnamejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchaiportnamejButtonActionPerformed(evt);
            }
        });

        airportnamejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Model Number", "Airlines Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airportnamejTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AirportnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(searchaiportnamejButton)))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AirportnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchaiportnamejButton))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(368, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchaiportnamejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchaiportnamejButtonActionPerformed
        // TODO add your handling code here:
         int i = 0, k=0;
        System.out.println("search");
        try
        {
            System.out.println("in try");
            anumber = AirportnamejTextField.getText();
            System.out.println(anumber);
        }
        catch(Exception e)
        {
            System.out.println("Some Exception");
            JOptionPane.showMessageDialog(null, "Plese enter correct values");
            i = 1;
        }
        System.out.println(ad.getAirplaneDirectory().size());
              
        
        
        
        for (Airplane ap : ad.getAirplaneDirectory())
        {
            System.out.println("In for");
          Object data[] = new Object[4];
        
        //String x = ap.getFlightNumber();
        if(anumber.equalsIgnoreCase(ap.getAirportName()))
        {
            k=1;
        data[0] = ap.getFlightNumber();
        data[1] = ap.getModelNumber();
        data[2] = ap.getAirlinesName();
        DefaultTableModel dm = (DefaultTableModel)airportnamejTable.getModel();
        //dm.setRowCount(0);
        dm.addRow(data);
        }
        }
        if(k==0)
        {
            JOptionPane.showMessageDialog(null, "Invalid Input. No such Airport Name. Plese enter correct values");
        }
        
        
    }//GEN-LAST:event_searchaiportnamejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AirportnamejTextField;
    private javax.swing.JTable airportnamejTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchaiportnamejButton;
    // End of variables declaration//GEN-END:variables
}
