/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.*;
import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rohan
 */
public class AvailofplanesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AvailofplanesJPanel
     */
    private AirplaneDirectory ad;
    private Airplane ap;
    private String anumber;
    public AvailofplanesJPanel(AirplaneDirectory ad) {
        initComponents();
        this.ad = ad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        airplanenonavailjTable = new javax.swing.JTable();
        AirplaneavailjLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        airplaneavailjTable1 = new javax.swing.JTable();
        searchflightavailjButton = new javax.swing.JButton();
        searchflightinavailjButton = new javax.swing.JButton();
        availablejRadioButton = new javax.swing.JRadioButton();
        NonAvailablejRadioButton = new javax.swing.JRadioButton();
        availabilityjTextField = new javax.swing.JTextField();

        airplanenonavailjTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        airplanenonavailjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Model Number", "Airlines Name", "Manufacturer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        airplanenonavailjTable.setAlignmentX(2.0F);
        airplanenonavailjTable.setAlignmentY(2.0F);
        airplanenonavailjTable.setIntercellSpacing(new java.awt.Dimension(3, 3));
        jScrollPane1.setViewportView(airplanenonavailjTable);

        AirplaneavailjLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AirplaneavailjLabel.setText("Airplane Availability");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Airplanes UnAvailablity");

        airplaneavailjTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        airplaneavailjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Model Number", "Airlines Name", "Manufacturer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        airplaneavailjTable1.setAlignmentX(2.0F);
        airplaneavailjTable1.setAlignmentY(2.0F);
        airplaneavailjTable1.setIntercellSpacing(new java.awt.Dimension(3, 3));
        jScrollPane2.setViewportView(airplaneavailjTable1);

        searchflightavailjButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        searchflightavailjButton.setText("Search Availability");
        searchflightavailjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchflightavailjButtonActionPerformed(evt);
            }
        });

        searchflightinavailjButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        searchflightinavailjButton.setText("Search Inavailability");
        searchflightinavailjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchflightinavailjButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(availablejRadioButton);
        availablejRadioButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        availablejRadioButton.setText("Available");
        availablejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availablejRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(NonAvailablejRadioButton);
        NonAvailablejRadioButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NonAvailablejRadioButton.setText("Not Available");
        NonAvailablejRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NonAvailablejRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(299, 299, 299)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(availablejRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AirplaneavailjLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(169, 169, 169)
                                    .addComponent(availabilityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(searchflightavailjButton)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(NonAvailablejRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchflightinavailjButton)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(AirplaneavailjLabel)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availablejRadioButton)
                    .addComponent(availabilityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchflightavailjButton))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(searchflightinavailjButton)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(NonAvailablejRadioButton)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchflightinavailjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchflightinavailjButtonActionPerformed
        // TODO add your handling code here:
       int i = 0, k=0;
        System.out.println("search");
        try
        {
            System.out.println("in try");
            anumber = availabilityjTextField.getText();
            System.out.println(anumber);
        }
        catch(Exception e)
        {
            System.out.println("Some Exception");
            JOptionPane.showMessageDialog(null, "Plese enter correct values");
            i = 1;
        }
        System.out.println(ad.getAirplaneDirectory().size());
              
        
         
       
        
        for (Airplane ap : ad.getAirplaneDirectory())
        {
            System.out.println("In for");
          Object data[] = new Object[4];
        
        //String x = ap.getFlightNumber();
        if(anumber.equalsIgnoreCase(ap.getAvailabilityOfPlanes()))
        {
            //k=1;
        data[0] = ap.getFlightNumber();
        data[1] = ap.getModelNumber();
        data[2] = ap.getAirlinesName();
        data[3] = ap.getAirportName();
        DefaultTableModel dm = (DefaultTableModel)airplanenonavailjTable.getModel();
        dm.addRow(data);
        }
        //if(k==0)
        {
            //JOptionPane.showMessageDialog(null, "Plese enter correct values");
        }
        } 
    }//GEN-LAST:event_searchflightinavailjButtonActionPerformed

    private void searchflightavailjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchflightavailjButtonActionPerformed
        // TODO add your handling code here:
        int k=0;
        System.out.println("search");
        try
        {
            System.out.println("in try");
            anumber = availabilityjTextField.getText();
            System.out.println(anumber);
        }
        catch(Exception e)
        {
            System.out.println("Some Exception");
            JOptionPane.showMessageDialog(null, "Plese enter correct values");
          
        }
        System.out.println(ad.getAirplaneDirectory().size());
              
        
         
        //dm.setRowCount(0);
        
        for (Airplane ap : ad.getAirplaneDirectory())
        {
            System.out.println("In for");
          Object data[] = new Object[4];
        
        //String x = ap.getFlightNumber();
        if(anumber.equalsIgnoreCase(ap.getAvailabilityOfPlanes()))
        {
            k=1;
        data[0] = ap.getFlightNumber();
        data[1] = ap.getModelNumber();
        data[2] = ap.getAirlinesName();
        data[3] = ap.getAirportName();
        DefaultTableModel dm = (DefaultTableModel)airplaneavailjTable1.getModel();
        dm.addRow(data);
        }
        if(k==0)
        {
            JOptionPane.showMessageDialog(null, "Plese enter correct values");
        }
        }
        
        
    }//GEN-LAST:event_searchflightavailjButtonActionPerformed

    private void availablejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availablejRadioButtonActionPerformed
        // TODO add your handling code here:
        availabilityjTextField.setText(availablejRadioButton.getText());
    }//GEN-LAST:event_availablejRadioButtonActionPerformed

    private void NonAvailablejRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NonAvailablejRadioButtonActionPerformed
        // TODO add your handling code here:
        availabilityjTextField.setText(NonAvailablejRadioButton.getText());
    }//GEN-LAST:event_NonAvailablejRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AirplaneavailjLabel;
    private javax.swing.JRadioButton NonAvailablejRadioButton;
    private javax.swing.JTable airplaneavailjTable1;
    private javax.swing.JTable airplanenonavailjTable;
    private javax.swing.JTextField availabilityjTextField;
    private javax.swing.JRadioButton availablejRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchflightavailjButton;
    private javax.swing.JButton searchflightinavailjButton;
    // End of variables declaration//GEN-END:variables
}
