/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
import java.io.File;
import java.io.FileFilter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohan
 */
public class firstAvailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form firstAvailJPanel
     */
    private AirplaneDirectory ad;
    private Airplane ap;
    private String anumber;
    public firstAvailJPanel(AirplaneDirectory ad) {
        initComponents();
        this.ad = ad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        firstavailjTable = new javax.swing.JTable();
        searchFirstjButton = new javax.swing.JButton();
        firstavailjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        availjCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        firstavailjTable.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        firstavailjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Model Number", "Airlines Name", "Airport Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(firstavailjTable);

        searchFirstjButton.setText("Search");
        searchFirstjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFirstjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Select to check Instant Availability:");

        availjCheckBox.setText("Available");
        availjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availjCheckBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Check very first Availability");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(searchFirstjButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(availjCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(firstavailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel3)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(availjCheckBox)
                    .addComponent(firstavailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchFirstjButton)
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFirstjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFirstjButtonActionPerformed
        // TODO add your handling code here:
        int  k=0;
        //System.out.println("search");
        try
        {
            System.out.println("in try");
            anumber = firstavailjTextField.getText();
            System.out.println(anumber);
        }
        catch(Exception e)
        {
            System.out.println("Some Exception");
            JOptionPane.showMessageDialog(null, "Invalid Input. Plese enter correct values");
            
        }
        System.out.println(ad.getAirplaneDirectory().size());
              
        
        
        
        for (Airplane ap : ad.getAirplaneDirectory())
        {
          //System.out.println("In for");
          Object data[] = new Object[4];
        
        //String x = ap.getFlightNumber();
        if(anumber.equalsIgnoreCase(ap.getAvailabilityOfPlanes()))
        {
        k=1;
        data[0] = ap.getFlightNumber();
        data[1] = ap.getModelNumber();
        data[2] = ap.getAirlinesName();
        data[3] = ap.getAirportName();
        DefaultTableModel dm = (DefaultTableModel)firstavailjTable.getModel();
        dm.setRowCount(0);
        dm.addRow(data);
        break;
        }
        }
        if(k==0)
        {
            JOptionPane.showMessageDialog(null, "Invalid Input. Plese enter correct values");
        }
        
        
       
      
        
      
   
    }//GEN-LAST:event_searchFirstjButtonActionPerformed

    private void availjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availjCheckBoxActionPerformed
        // TODO add your handling code here:
        firstavailjTextField.setText(availjCheckBox.getText());
    }//GEN-LAST:event_availjCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox availjCheckBox;
    private javax.swing.JTable firstavailjTable;
    private javax.swing.JTextField firstavailjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchFirstjButton;
    // End of variables declaration//GEN-END:variables
}
