/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.SplitPane;

/**
 *
 * @author Rohan
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private ArrayList <Airplane> ap;
    private AirplaneDirectory ad;
    public MainJFrame() {
        initComponents();
        ad = new AirplaneDirectory();
        loadCsv();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        SplitPane = new javax.swing.JSplitPane();
        CreatejPanel = new javax.swing.JPanel();
        selectfromjComboBox = new javax.swing.JComboBox<>();
        searchjButton = new javax.swing.JButton();
        viewjButton = new javax.swing.JButton();
        LUDjButton = new javax.swing.JButton();
        FirstjButton = new javax.swing.JButton();
        setdefaultjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setDividerLocation(250);

        selectfromjComboBox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        selectfromjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select from the list", "Aircraft availability", "Manufacturer Name", "Manufacturer Year", "Seat Availability", "Flight Number", "Model Number", "Airlines Name", "Airport Name", "Expired Maintenance" }));
        selectfromjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectfromjComboBoxActionPerformed(evt);
            }
        });

        searchjButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        searchjButton.setText("Search");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        viewjButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        viewjButton.setText("View ");
        viewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewjButtonActionPerformed(evt);
            }
        });

        LUDjButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LUDjButton.setText("Catalog Last Update date");
        LUDjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LUDjButtonActionPerformed(evt);
            }
        });

        FirstjButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FirstjButton.setText("Check Instant Availablity");
        FirstjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstjButtonActionPerformed(evt);
            }
        });

        setdefaultjButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        setdefaultjButton.setText("Set Default Preferences");
        setdefaultjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setdefaultjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Select the specific search criteria");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Set your preferences");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("To check instant availability select:");

        javax.swing.GroupLayout CreatejPanelLayout = new javax.swing.GroupLayout(CreatejPanel);
        CreatejPanel.setLayout(CreatejPanelLayout);
        CreatejPanelLayout.setHorizontalGroup(
            CreatejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreatejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatejPanelLayout.createSequentialGroup()
                        .addComponent(selectfromjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CreatejPanelLayout.createSequentialGroup()
                        .addGroup(CreatejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstjButton)
                            .addGroup(CreatejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(viewjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(setdefaultjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LUDjButton)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CreatejPanelLayout.setVerticalGroup(
            CreatejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreatejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectfromjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchjButton))
                .addGap(51, 51, 51)
                .addComponent(LUDjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstjButton)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(setdefaultjButton)
                .addGap(74, 74, 74)
                .addComponent(viewjButton)
                .addContainerGap())
        );

        SplitPane.setLeftComponent(CreatejPanel);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel4.setText("Personal Trip Manager");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(180, 20, 540, 102);
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 100, 800, 690);

        SplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1340, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setdefaultjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setdefaultjButtonActionPerformed
        // TODO add your handling code here:
        setPreferJPanel search = new setPreferJPanel(ad);
        SplitPane.setRightComponent(search);
    }//GEN-LAST:event_setdefaultjButtonActionPerformed

    private void FirstjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstjButtonActionPerformed
        // TODO add your handling code here:
        firstAvailJPanel first = new firstAvailJPanel(ad);
        SplitPane.setRightComponent(first);
    }//GEN-LAST:event_FirstjButtonActionPerformed

    private void LUDjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LUDjButtonActionPerformed
        // TODO add your handling code here:
        LastModifiedJPanel lastModified = new LastModifiedJPanel(ad);
        SplitPane.setRightComponent(lastModified);
    }//GEN-LAST:event_LUDjButtonActionPerformed

    private void viewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewjButtonActionPerformed
        // TODO add your handling code here:
        viewDefaultJPanel vd = new viewDefaultJPanel(ad);
        SplitPane.setRightComponent(vd);
    }//GEN-LAST:event_viewjButtonActionPerformed

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        // TODO add your handling code here:
        String values = (String) selectfromjComboBox.getSelectedItem();

        if (values.equalsIgnoreCase("Aircraft availability"))
        {
            AvailofplanesJPanel availofplanes = new AvailofplanesJPanel(ad);
            SplitPane.setRightComponent(availofplanes);
        }

        if (values.equalsIgnoreCase("Flight Number"))
        {
            EnterFlightNumberJPanel enterflightno = new EnterFlightNumberJPanel(ad);
            SplitPane.setRightComponent(enterflightno);
        }

        if (values.equalsIgnoreCase("Model Number"))
        {
            ModelNumberJPanel entermodelno = new ModelNumberJPanel(ad);
            SplitPane.setRightComponent(entermodelno);
        }

        if (values.equalsIgnoreCase("Airlines Name"))
        {
            ManufacturerNameJPanel entermanfacname = new ManufacturerNameJPanel(ad);
            SplitPane.setRightComponent(entermanfacname);
        }

        if (values.equalsIgnoreCase("Manufacturer Name"))
        {
            AirplanemanJPanel airplaneman = new AirplanemanJPanel(ad);
            SplitPane.setRightComponent(airplaneman);
        }

        if (values.equalsIgnoreCase("Manufacturer Year"))
        {
            ManufacturerYearJPanel entermanufacyear = new ManufacturerYearJPanel(ad);
            SplitPane.setRightComponent(entermanufacyear);
        }

        if (values.equalsIgnoreCase("Seat Availability"))
        {
            AvailibilityofSeatsJPanel seatavail = new AvailibilityofSeatsJPanel(ad);
            SplitPane.setRightComponent(seatavail);
        }

        if (values.equalsIgnoreCase("Airport Name"))
        {
            AirportNameJPanel enterairportname = new AirportNameJPanel(ad);
            SplitPane.setRightComponent(enterairportname);
        }

        if (values.equalsIgnoreCase("Expired Maintenance"))
        {
            ExpMainJPanel flightmain = new ExpMainJPanel(ad);
            SplitPane.setRightComponent(flightmain);
        }

        if (values.equalsIgnoreCase("Aircraft availability"))
        {
            AvailofplanesJPanel availofplanes = new AvailofplanesJPanel(ad);
            SplitPane.setRightComponent(availofplanes);
        }
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void selectfromjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectfromjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectfromjComboBoxActionPerformed

    public void  loadCsv()
    {
        String filename = "src\\Interface\\Airlines Management.csv";
        File file = new File (filename);
        try
        {
            Scanner inputStream = new Scanner(file);
            while (inputStream.hasNext())
            {
                String data = inputStream.nextLine();
                String [] values = data.split(",");
                Airplane ap = new Airplane();
                //System.out.println(values[4]);
                ap.setFlightNumber(values[0]);
                ap.setModelNumber(values[1]);
                ap.setAirlinesName(values[2]);
                ap.setManufacName(values[3]);
                String trail=values[4];
                ap.setManufacYear(Integer.parseInt(trail));
                String seat=values[5];
                ap.setAvailabilityOfSeats(Integer.parseInt(seat));
                ap.setAirportName(values[6]);
                ap.setExpiredMain(values[7]);
                ap.setAvailabilityOfPlanes(values[8]);
                ad.getAirplaneDirectory().add(ap);
            }
           
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreatejPanel;
    private javax.swing.JButton FirstjButton;
    private javax.swing.JButton LUDjButton;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton searchjButton;
    private javax.swing.JComboBox<String> selectfromjComboBox;
    private javax.swing.JButton setdefaultjButton;
    private javax.swing.JButton viewjButton;
    // End of variables declaration//GEN-END:variables
}
